.TH "katapayadi" "1" "19 September 2024" "katapayadi" "Katapayadi"

.SH NAME
.B katapayadi
- conversion of Sanskrit words to numerical values


.SH SYNOPSIS
.SY katapayadi
.RI [ "TEXT ARGUMENTS" ]...
.YS


.SH INTRODUCTION
.B katapayadi
is a small console utility that can convert Sanskrit words to numbers according
to the katapayadi system.


.SH SEE ALSO
.I https://en.wikipedia.org/wiki/Katapayadi_system


.SH REPORTING BUGS
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you are and the bug is still present, you can
report it on the GitHub issues tracker:
.IR https://github.com/vlastavesely/katapayadi/issues .


.SH LICENSE AND WARRANTY
Copyright © 2024  Vlasta Vesely
.RI < vlastavesely@proton.me >.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the
Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
